server:
  host: http://localhost:8080
  port: 8080
  contextPath: /

db:
  host: 127.0.0.1
  port: 5432
  dbname: zocket
  user: zocket
  password: zocket#123

kafka:
  bootstrapServer: localhost:9092
  topic: products

files:
  basePath: /Users/bijaysharma/Documents/zocket/images